"""SQLAlchemy session listeners that populate `audit_logs` automatically.

Design notes
------------
- We hook `before_flush` to inspect pending changes (we need access to the
  attribute history *before* it is reset), then stage the resulting audit
  payloads on `session.info`. After the primary flush completes (`after_flush`)
  the staged `AuditLog` instances are added back to the session — by that
  point any newly inserted row has its autogenerated `id`, which is what we
  store in `audit_logs.record_id`.

- A separate `do_orm_execute` hook covers bulk-statement paths
  (`Query.update()`, `Query.delete()`, `session.execute(update(...))`,
  `session.execute(delete(...))`) on the audited models. The hook fetches the
  affected primary keys *before* the statement runs so we can emit one audit
  row per affected record with accurate old/new values.

- Bulk-import pipelines mark their session with `db.info["skip_audit"] = True`
  (see `bulk_import_pseudocode.md`) so file imports do not pollute
  `audit_logs`; revisions are tracked separately.

- Status / approve / reject / assign actions are encoded by inspecting which
  columns changed. Pure UPDATE (no status column touched) maps to
  `AuditAction.update`. Explicit semantic actions can also be recorded via
  `app.services.audit_service.AuditService.record(...)` when business intent
  matters more than the column-level diff.

- DB-level cascade (`ondelete="CASCADE"`) on FKs *pointing at* audited models
  would bypass these listeners. The current schema does not exercise that
  path (the five audited models are never deleted by cascade from another
  table), but callers introducing such an FK in future should switch the
  child relationship to ORM-level `cascade="all, delete-orphan"` or emit an
  explicit `AuditService.record(...)` call.
"""

from __future__ import annotations

import datetime as _dt
import enum as _enum
import logging
from typing import Any

from sqlalchemy import event, inspect, select
from sqlalchemy.orm import Session
from sqlalchemy.sql import Delete, Update

from app.core.audit_context import get_audit_context
from app.models.audit.audit_log import AuditAction, AuditLog, AuditModule


logger = logging.getLogger(__name__)


# Mapping ORM class name -> AuditModule. Looked up by class name (rather than
# by importing each class here) to avoid a circular-import risk during model
# auto-discovery in `app.models.__init__`.
_AUDITED_MODELS: dict[str, AuditModule] = {
    "User": AuditModule.user,
    "BuildPlan": AuditModule.build_plan,
    "BuildRequest": AuditModule.build_request,
    "Shipping": AuditModule.shipping,
    "Component": AuditModule.component,
}

# Columns we never want to persist in old_value / new_value JSON blobs.
_SENSITIVE_FIELDS: frozenset[str] = frozenset(
    {
        "password_hash",
        "token_version",
        "failed_login_attempts",
        "locked_until",
    }
)


def _jsonify(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, _enum.Enum):
        return value.value
    if isinstance(value, (_dt.datetime, _dt.date)):
        return value.isoformat()
    if isinstance(value, (str, int, float, bool)):
        return value
    return str(value)


def _serialize(obj: Any) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for col in obj.__table__.columns:
        if col.name in _SENSITIVE_FIELDS:
            continue
        out[col.name] = _jsonify(getattr(obj, col.name, None))
    return out


def _diff(obj: Any) -> tuple[dict[str, Any], dict[str, Any]]:
    """Return (old, new) JSON-friendly diffs for changed mapped columns."""
    state = inspect(obj)
    old: dict[str, Any] = {}
    new: dict[str, Any] = {}
    column_keys = {c.name for c in obj.__table__.columns}
    for attr in state.attrs:
        if attr.key not in column_keys or attr.key in _SENSITIVE_FIELDS:
            continue
        hist = attr.history
        if not hist.has_changes():
            continue
        o = hist.deleted[0] if hist.deleted else None
        n = hist.added[0] if hist.added else None
        old[attr.key] = _jsonify(o)
        new[attr.key] = _jsonify(n)
    return old, new


def _action_for_update(new: dict[str, Any]) -> AuditAction:
    """Map a column-level diff to a semantic AuditAction."""
    if "status" in new:
        status = new["status"]
        if isinstance(status, str):
            lowered = status.lower()
            if lowered == "approved":
                return AuditAction.approve
            if lowered == "rejected":
                return AuditAction.reject
        return AuditAction.status_change
    # Generic assign/unassign heuristic for *_id handler / assignee columns.
    handler_keys = {"handler_id", "assignee_id", "requestor_id"}
    touched = handler_keys.intersection(new.keys())
    if touched:
        any_set = any(new[k] is not None for k in touched)
        return AuditAction.assign if any_set else AuditAction.unassign
    return AuditAction.update


def _module_for(obj: Any) -> AuditModule | None:
    return _AUDITED_MODELS.get(type(obj).__name__)


def _stage(session: Session, payload: dict[str, Any]) -> None:
    session.info.setdefault("_audit_pending", []).append(payload)


def _before_flush(session: Session, flush_context, instances) -> None:  # noqa: ARG001
    if session.info.get("skip_audit"):
        return

    ctx = get_audit_context()
    user_id = ctx.get("user_id")
    if not user_id:
        # `audit_logs.user_id` is NOT NULL. Without an attributable user the
        # safest behaviour is to skip — the alternative (raising) would break
        # legitimate non-HTTP code paths like seeding.
        return

    ip = ctx.get("ip")
    ua = ctx.get("user_agent")

    for obj in session.new:
        module = _module_for(obj)
        if module is None:
            continue
        _stage(
            session,
            {
                "obj": obj,
                "module": module,
                "action": AuditAction.create,
                "old_value": None,
                "new_value": _serialize(obj),
                "user_id": user_id,
                "ip": ip,
                "user_agent": ua,
            },
        )

    for obj in session.dirty:
        module = _module_for(obj)
        if module is None:
            continue
        if not session.is_modified(obj, include_collections=False):
            continue
        old, new = _diff(obj)
        if not new:
            continue
        _stage(
            session,
            {
                "obj": obj,
                "module": module,
                "action": _action_for_update(new),
                "old_value": old,
                "new_value": new,
                "user_id": user_id,
                "ip": ip,
                "user_agent": ua,
            },
        )

    for obj in session.deleted:
        module = _module_for(obj)
        if module is None:
            continue
        _stage(
            session,
            {
                "obj": obj,
                "module": module,
                "action": AuditAction.delete,
                "old_value": _serialize(obj),
                "new_value": None,
                "user_id": user_id,
                "ip": ip,
                "user_agent": ua,
            },
        )


def _after_flush(session: Session, flush_context) -> None:  # noqa: ARG001
    pending = session.info.pop("_audit_pending", None)
    if not pending:
        return

    for entry in pending:
        obj = entry["obj"]
        record_id = getattr(obj, "id", None)
        if record_id is None:
            # Shouldn't happen post-flush, but guard against weird states
            # (e.g. mapper without autoload id) rather than failing the
            # whole transaction.
            logger.warning(
                "audit: skipping %s/%s — record_id unavailable",
                entry["module"].value,
                entry["action"].value,
            )
            continue

        session.add(
            AuditLog(
                user_id=entry["user_id"],
                module=entry["module"],
                action=entry["action"],
                record_id=record_id,
                old_value=entry["old_value"],
                new_value=entry["new_value"],
                ip_address=entry["ip"],
                user_agent=entry["user_agent"],
            )
        )


_REGISTERED = False


def _extract_update_values(stmt: Update) -> dict[str, Any]:
    """Best-effort extraction of the SET clause from a Core/ORM Update.

    SQLAlchemy's internal attribute for the values dict has changed shape
    between minor versions; we try the public-ish ``_values`` mapping and
    fall back to an empty dict so a future SA upgrade can never break audits.
    """
    raw: Any = getattr(stmt, "_values", None)
    if raw is None:
        return {}
    out: dict[str, Any] = {}
    try:
        items = raw.items() if hasattr(raw, "items") else list(raw)
    except Exception:  # noqa: BLE001
        return {}
    for col, val in items:
        key = getattr(col, "key", None) or getattr(col, "name", None) or str(col)
        if key in _SENSITIVE_FIELDS:
            continue
        # ``val`` may be a bind parameter, literal, or SQL expression. Only
        # store scalar literals; everything else is recorded as None to make
        # it obvious the value was computed server-side.
        literal = getattr(val, "value", val)
        if isinstance(literal, (str, int, float, bool, type(None), _dt.date, _dt.datetime, _enum.Enum)):
            out[key] = _jsonify(literal)
        else:
            out[key] = None
    return out


def _do_orm_execute(state) -> None:
    """Intercept bulk Update/Delete on audited tables and emit audit rows.

    Pre-fetches the matching primary keys + current column values so we can
    record per-row old/new diffs even though the bulk statement bypasses the
    unit of work.
    """
    if not (state.is_update or state.is_delete):
        return
    # `is_update`/`is_delete` are True for INSERT...RETURNING too in some SA
    # builds; double-check the statement class explicitly.
    statement = state.statement
    if not isinstance(statement, (Update, Delete)):
        return

    session: Session = state.session
    if session.info.get("skip_audit"):
        return

    mapper = getattr(state, "bind_mapper", None)
    if mapper is None:
        return
    module = _AUDITED_MODELS.get(mapper.class_.__name__)
    if module is None:
        return

    ctx = get_audit_context()
    user_id = ctx.get("user_id")
    if not user_id:
        return

    target_cls = mapper.class_
    whereclause = statement.whereclause

    # SELECT the rows that will be affected so we can capture pre-state.
    sel = select(target_cls)
    if whereclause is not None:
        sel = sel.where(whereclause)
    try:
        affected = session.execute(sel).scalars().all()
    except Exception:  # noqa: BLE001 - never fail the original op for audit purposes
        logger.exception("audit: failed to pre-fetch bulk %s rows", target_cls.__name__)
        return

    snapshots = [(getattr(obj, "id", None), _serialize(obj)) for obj in affected]

    if isinstance(statement, Delete):
        for record_id, old in snapshots:
            if record_id is None:
                continue
            session.add(
                AuditLog(
                    user_id=user_id,
                    module=module,
                    action=AuditAction.delete,
                    record_id=record_id,
                    old_value=old,
                    new_value=None,
                    ip_address=ctx.get("ip"),
                    user_agent=ctx.get("user_agent"),
                )
            )
        return

    # UPDATE: extract the SET clause and derive a semantic action.
    values = _extract_update_values(statement)
    if not values:
        return
    action = _action_for_update(values)
    for record_id, old in snapshots:
        if record_id is None:
            continue
        old_subset = {k: old.get(k) for k in values.keys()}
        session.add(
            AuditLog(
                user_id=user_id,
                module=module,
                action=action,
                record_id=record_id,
                old_value=old_subset,
                new_value=values,
                ip_address=ctx.get("ip"),
                user_agent=ctx.get("user_agent"),
            )
        )


def register_audit_listeners() -> None:
    """Attach the audit listeners to every SQLAlchemy `Session`.

    Idempotent — safe to call multiple times (e.g. during test reloads).
    """
    global _REGISTERED
    if _REGISTERED:
        return
    event.listen(Session, "before_flush", _before_flush)
    event.listen(Session, "after_flush", _after_flush)
    event.listen(Session, "do_orm_execute", _do_orm_execute)
    _REGISTERED = True
