"""initial schema

Revision ID: 03d3f3592f83
Revises: 
Create Date: 2026-05-26 08:39:30.542094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d3f3592f83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_action_categories_id'), 'action_categories', ['id'], unique=False)
    op.create_table('attribute_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('build_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notes')
    )
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_table('config_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_numbers_value'), 'config_numbers', ['value'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_families_code'), 'families', ['code'], unique=True)
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_table('form_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_factors_id'), 'form_factors', ['id'], unique=False)
    op.create_index(op.f('ix_form_factors_name'), 'form_factors', ['name'], unique=True)
    op.create_table('forwarders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forwarders_id'), 'forwarders', ['id'], unique=False)
    op.create_index(op.f('ix_forwarders_name'), 'forwarders', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('silicon_steppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silicon_steppings_name'), 'silicon_steppings', ['name'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('support_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_activities_name'), 'support_activities', ['name'], unique=True)
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_index(op.f('ix_tests_name'), 'tests', ['name'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('build_plan_build_descs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_activity_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['support_activity_id'], ['support_activities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('support_activity_id', 'description', name='uq_build_desc_per_activity')
    )
    op.create_table('component_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('slot_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'slot_code', name='uq_component_slot')
    )
    op.create_index(op.f('ix_component_slots_id'), 'component_slots', ['id'], unique=False)
    op.create_table('component_suppliers',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id', 'supplier_id')
    )
    op.create_table('family_form_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('form_factor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_factor_id'], ['form_factors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_form_factors_id'), 'family_form_factors', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('action_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_category_id'], ['action_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('support_activity_build_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_activity_id', sa.Integer(), nullable=False),
    sa.Column('build_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_note_id'], ['build_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['support_activity_id'], ['support_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('support_activity_id', 'build_note_id', name='uq_support_activity_build_note')
    )
    op.create_table('test_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'detail', name='uq_test_detail')
    )
    op.create_index(op.f('ix_test_details_id'), 'test_details', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_login', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_', sa.DateTime(), nullable=True),
    sa.Column('legacy_ref', sa.String(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('legacy_ref')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('line1', sa.String(), nullable=True),
    sa.Column('line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.Enum('user', 'build_plan', 'build_request', 'shipping', 'component', 'log_report', name='auditmodule'), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'status_change', 'assign', 'unassign', 'approve', 'reject', name='auditaction'), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_module_action', 'audit_logs', ['module', 'action'], unique=False)
    op.create_index('ix_audit_logs_record_id', 'audit_logs', ['record_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('build_plan_access',
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.Column('family_form_factor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.Enum('owner', 'editor', name='build_plan_access_type'), nullable=False),
    sa.ForeignKeyConstraint(['family_form_factor_id'], ['family_form_factors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('access_id'),
    sa.UniqueConstraint('family_form_factor_id', 'user_id', name='uq_build_plan_access_family_form_factor_user')
    )
    op.create_index(op.f('ix_build_plan_access_access_id'), 'build_plan_access', ['access_id'], unique=False)
    op.create_table('build_plan_import_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('work_week', sa.Integer(), nullable=True),
    sa.Column('work_year', sa.Integer(), nullable=True),
    sa.Column('file_revision', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'success', 'failed', 'skipped', name='buildplanimportstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_build_plan_import_files_content_hash'), 'build_plan_import_files', ['content_hash'], unique=False)
    op.create_index('ix_build_plan_import_files_created_at', 'build_plan_import_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_build_plan_import_files_id'), 'build_plan_import_files', ['id'], unique=False)
    op.create_index('ix_build_plan_import_files_status', 'build_plan_import_files', ['status'], unique=False)
    op.create_table('build_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('family_form_factor_id', sa.Integer(), nullable=False),
    sa.Column('config_number_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'underReview', 'cancelled', 'rejected', 'approved', 'planned', 'locked', 'completed', 'none', name='buildrequeststatus'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('previous_build_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_number_id'], ['config_numbers.id'], ),
    sa.ForeignKeyConstraint(['family_form_factor_id'], ['family_form_factors.id'], ),
    sa.ForeignKeyConstraint(['previous_build_request_id'], ['build_requests.id'], ),
    sa.ForeignKeyConstraint(['requestor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_requests_config_number_id'), 'build_requests', ['config_number_id'], unique=False)
    op.create_index(op.f('ix_build_requests_family_form_factor_id'), 'build_requests', ['family_form_factor_id'], unique=False)
    op.create_index(op.f('ix_build_requests_requestor_id'), 'build_requests', ['requestor_id'], unique=False)
    op.create_index(op.f('ix_build_requests_status'), 'build_requests', ['status'], unique=False)
    op.create_table('component_supplier_families',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id', 'supplier_id'], ['component_suppliers.component_id', 'component_suppliers.supplier_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id', 'supplier_id', 'family_id')
    )
    op.create_index('ix_csf_component_supplier', 'component_supplier_families', ['component_id', 'supplier_id'], unique=False)
    op.create_index('ix_csf_family', 'component_supplier_families', ['family_id'], unique=False)
    op.create_table('log_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('actual_behavior', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('screenshot_url', sa.String(), nullable=True),
    sa.Column('developer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pm_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'family_id', name='uq_pm_family_user_family')
    )
    op.create_index(op.f('ix_pm_families_family_id'), 'pm_families', ['family_id'], unique=False)
    op.create_index(op.f('ix_pm_families_id'), 'pm_families', ['id'], unique=False)
    op.create_index('ix_pm_families_user_family', 'pm_families', ['user_id', 'family_id'], unique=False)
    op.create_index(op.f('ix_pm_families_user_id'), 'pm_families', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('shipping_import_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'success', 'failed', 'skipped', name='shippingimportstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_shipping_import_files_content_hash'), 'shipping_import_files', ['content_hash'], unique=False)
    op.create_index('ix_shipping_import_files_created_at', 'shipping_import_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipping_import_files_id'), 'shipping_import_files', ['id'], unique=False)
    op.create_index('ix_shipping_import_files_status', 'shipping_import_files', ['status'], unique=False)
    op.create_table('shippings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_number_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('forwarder_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('ship_date', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'shipped_out', 'delivered', 'completed', name='shipping_status'), nullable=False),
    sa.ForeignKeyConstraint(['config_number_id'], ['config_numbers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['forwarder_id'], ['forwarders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippings_config_number_id'), 'shippings', ['config_number_id'], unique=False)
    op.create_index(op.f('ix_shippings_id'), 'shippings', ['id'], unique=False)
    op.create_index(op.f('ix_shippings_recipient_user_id'), 'shippings', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_shippings_status'), 'shippings', ['status'], unique=False)
    op.create_table('stored_file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('storage_path'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_stored_file_file_id'), 'stored_file', ['file_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('build_plan_import_shipping_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_file_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('responsibility', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_file_id'], ['build_plan_import_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_file_id', 'responsibility', 'name', 'address', name='uq_build_plan_import_shipping_info_row')
    )
    op.create_index('ix_build_plan_import_shipping_infos_file', 'build_plan_import_shipping_infos', ['import_file_id'], unique=False)
    op.create_index(op.f('ix_build_plan_import_shipping_infos_id'), 'build_plan_import_shipping_infos', ['id'], unique=False)
    op.create_index(op.f('ix_build_plan_import_shipping_infos_import_file_id'), 'build_plan_import_shipping_infos', ['import_file_id'], unique=False)
    op.create_table('build_plan_import_si_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_file_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('si_description', sa.String(length=500), nullable=True),
    sa.Column('si_lot_numbers', sa.String(length=500), nullable=True),
    sa.Column('class_test_rev', sa.String(length=255), nullable=True),
    sa.Column('request_qty', sa.Integer(), nullable=True),
    sa.Column('request_dock_date', sa.String(length=64), nullable=True),
    sa.Column('commit_qty', sa.Integer(), nullable=True),
    sa.Column('commit_dock_date', sa.String(length=64), nullable=True),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('actual_dock_date', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_file_id'], ['build_plan_import_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_build_plan_import_si_rows_file', 'build_plan_import_si_rows', ['import_file_id'], unique=False)
    op.create_index(op.f('ix_build_plan_import_si_rows_id'), 'build_plan_import_si_rows', ['id'], unique=False)
    op.create_index(op.f('ix_build_plan_import_si_rows_import_file_id'), 'build_plan_import_si_rows', ['import_file_id'], unique=False)
    op.create_table('build_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_form_factor_id', sa.Integer(), nullable=False),
    sa.Column('support_activity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('plan', 'hold', 'done', 'cancelled', 'new', name='buildplanstatus'), nullable=False),
    sa.Column('build_description_id', sa.Integer(), nullable=False),
    sa.Column('config_number_id', sa.Integer(), nullable=False),
    sa.Column('latest_revision_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_file_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_file_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('mm_number', sa.String(), nullable=True),
    sa.Column('ta_number', sa.String(), nullable=True),
    sa.Column('pba_number', sa.String(), nullable=True),
    sa.Column('as_number', sa.String(), nullable=True),
    sa.Column('special_instruction', sa.String(), nullable=True),
    sa.Column('build_start_date', sa.DateTime(), nullable=True),
    sa.Column('ship_date', sa.DateTime(), nullable=True),
    sa.Column('required_quantity', sa.Integer(), nullable=True),
    sa.Column('estimated_yield', sa.Integer(), nullable=True),
    sa.Column('build_start_quantity', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('work_week', sa.Integer(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['build_description_id'], ['build_plan_build_descs.id'], ),
    sa.ForeignKeyConstraint(['config_number_id'], ['config_numbers.id'], ),
    sa.ForeignKeyConstraint(['family_form_factor_id'], ['family_form_factors.id'], ),
    sa.ForeignKeyConstraint(['first_seen_file_id'], ['build_plan_import_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_seen_file_id'], ['build_plan_import_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['latest_revision_id'], ['build_plan_revisions.id'], name='fk_build_plans_latest_revision_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['support_activity_id'], ['support_activities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_form_factor_id', 'config_number_id', name='uq_build_plan_family_form_factor_config_number')
    )
    op.create_index('ix_build_plans_build_start_date', 'build_plans', ['build_start_date'], unique=False)
    op.create_index('ix_build_plans_config_number_id', 'build_plans', ['config_number_id'], unique=False)
    op.create_index('ix_build_plans_family_form_factor_id', 'build_plans', ['family_form_factor_id'], unique=False)
    op.create_index(op.f('ix_build_plans_is_imported'), 'build_plans', ['is_imported'], unique=False)
    op.create_index(op.f('ix_build_plans_latest_revision_id'), 'build_plans', ['latest_revision_id'], unique=False)
    op.create_index('ix_build_plans_ship_date', 'build_plans', ['ship_date'], unique=False)
    op.create_index('ix_build_plans_status', 'build_plans', ['status'], unique=False)
    op.create_index('ix_build_plans_support_activity_id', 'build_plans', ['support_activity_id'], unique=False)
    op.create_index(op.f('ix_build_plans_work_week'), 'build_plans', ['work_week'], unique=False)
    op.create_index(op.f('ix_build_plans_year'), 'build_plans', ['year'], unique=False)
    op.create_table('log_report_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['log_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_build_requests',
    sa.Column('requestor_id', sa.Integer(), nullable=False),
    sa.Column('build_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_request_id'], ['build_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requestor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requestor_id', 'build_request_id')
    )
    op.create_table('build_plan_access_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.Enum('owner', 'editor', name='build_plan_access_type'), nullable=False),
    sa.ForeignKeyConstraint(['build_plan_id'], ['build_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_plan_id', 'user_id', name='uq_bp_access_override_plan_user')
    )
    op.create_index(op.f('ix_build_plan_access_overrides_id'), 'build_plan_access_overrides', ['id'], unique=False)
    op.create_table('build_plan_build_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_plan_id', sa.Integer(), nullable=False),
    sa.Column('build_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_note_id'], ['build_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['build_plan_id'], ['build_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_plan_id', 'build_note_id', name='uq_build_plan_build_note')
    )
    op.create_table('build_plan_build_requests',
    sa.Column('build_plan_id', sa.Integer(), nullable=False),
    sa.Column('build_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_plan_id'], ['build_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['build_request_id'], ['build_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_plan_id', 'build_request_id')
    )
    op.create_index('ix_build_plan_build_requests_build_plan_id', 'build_plan_build_requests', ['build_plan_id'], unique=False)
    op.create_table('build_plan_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_plan_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('is_key', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['build_plan_id'], ['build_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['component_slots.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_plan_id', 'component_id', 'slot_id', name='uq_plan_component_slot')
    )
    op.create_index(op.f('ix_build_plan_components_build_plan_id'), 'build_plan_components', ['build_plan_id'], unique=False)
    op.create_index('ix_build_plan_components_component_id', 'build_plan_components', ['component_id'], unique=False)
    op.create_index(op.f('ix_build_plan_components_id'), 'build_plan_components', ['id'], unique=False)
    op.create_table('build_plan_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_plan_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('import_file_id', sa.Integer(), nullable=True),
    sa.Column('work_year', sa.Integer(), nullable=True),
    sa.Column('work_week', sa.Integer(), nullable=True),
    sa.Column('file_revision', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('status_at_revision', sa.Enum('plan', 'hold', 'done', 'cancelled', 'new', name='buildplanstatus'), nullable=False),
    sa.Column('is_imported', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_plan_id'], ['build_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_file_id'], ['build_plan_import_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_plan_id', 'revision_number', name='uq_build_plan_revision_number')
    )
    op.create_index('ix_build_plan_revisions_chrono', 'build_plan_revisions', ['build_plan_id', 'work_year', 'work_week', 'file_revision'], unique=False)
    op.create_table('build_plan_shippings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_plan_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('requestor_user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['build_plan_id'], ['build_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requestor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_plan_id', 'recipient_user_id', 'requestor_user_id', name='uq_build_plan_shipping_recipient_requestor')
    )
    op.create_index(op.f('ix_build_plan_shippings_build_plan_id'), 'build_plan_shippings', ['build_plan_id'], unique=False)
    op.create_index(op.f('ix_build_plan_shippings_id'), 'build_plan_shippings', ['id'], unique=False)
    op.create_index('ix_build_plan_shippings_plan_recipient', 'build_plan_shippings', ['build_plan_id', 'recipient_user_id'], unique=False)
    op.create_index(op.f('ix_build_plan_shippings_recipient_user_id'), 'build_plan_shippings', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_build_plan_shippings_requestor_user_id'), 'build_plan_shippings', ['requestor_user_id'], unique=False)
    op.create_table('build_plan_silicon_steppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_plan_id', sa.Integer(), nullable=False),
    sa.Column('silicon_stepping_id', sa.Integer(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['build_plan_id'], ['build_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['silicon_stepping_id'], ['silicon_steppings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_plan_id', 'silicon_stepping_id', 'suffix', name='uq_build_plan_silicon_stepping_suffix')
    )
    op.create_table('build_plan_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_plan_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['build_plan_id'], ['build_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_detail_id'], ['test_details.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_plan_id', 'test_id', 'test_detail_id', name='uq_build_plan_test_detail')
    )
    op.create_index('ix_build_plan_tests_build_plan_id', 'build_plan_tests', ['build_plan_id'], unique=False)
    op.create_index(op.f('ix_build_plan_tests_id'), 'build_plan_tests', ['id'], unique=False)
    op.create_index('ix_build_plan_tests_test_id', 'build_plan_tests', ['test_id'], unique=False)
    op.create_table('quantity_stored_in_warehouse',
    sa.Column('buildplan_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_stored', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buildplan_id'], ['build_plans.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('buildplan_id', 'warehouse_id')
    )
    op.create_table('build_plan_import_file_touches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_file_id', sa.Integer(), nullable=False),
    sa.Column('build_plan_id', sa.Integer(), nullable=False),
    sa.Column('matched_revision_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_plan_id'], ['build_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_file_id'], ['build_plan_import_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_revision_id'], ['build_plan_revisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_file_id', 'build_plan_id', name='uq_import_file_touch_file_plan')
    )
    op.create_table('component_attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_plan_component_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('value_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute_definitions.id'], ),
    sa.ForeignKeyConstraint(['build_plan_component_id'], ['build_plan_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_plan_component_id', 'attribute_id', name='uq_build_plan_component_attribute')
    )
    op.create_index('ix_component_attribute_values_attribute_id', 'component_attribute_values', ['attribute_id'], unique=False)
    op.create_index('ix_component_attribute_values_bpc_id', 'component_attribute_values', ['build_plan_component_id'], unique=False)
    op.create_index(op.f('ix_component_attribute_values_id'), 'component_attribute_values', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_component_attribute_values_id'), table_name='component_attribute_values')
    op.drop_index('ix_component_attribute_values_bpc_id', table_name='component_attribute_values')
    op.drop_index('ix_component_attribute_values_attribute_id', table_name='component_attribute_values')
    op.drop_table('component_attribute_values')
    op.drop_table('build_plan_import_file_touches')
    op.drop_table('quantity_stored_in_warehouse')
    op.drop_index('ix_build_plan_tests_test_id', table_name='build_plan_tests')
    op.drop_index(op.f('ix_build_plan_tests_id'), table_name='build_plan_tests')
    op.drop_index('ix_build_plan_tests_build_plan_id', table_name='build_plan_tests')
    op.drop_table('build_plan_tests')
    op.drop_table('build_plan_silicon_steppings')
    op.drop_index(op.f('ix_build_plan_shippings_requestor_user_id'), table_name='build_plan_shippings')
    op.drop_index(op.f('ix_build_plan_shippings_recipient_user_id'), table_name='build_plan_shippings')
    op.drop_index('ix_build_plan_shippings_plan_recipient', table_name='build_plan_shippings')
    op.drop_index(op.f('ix_build_plan_shippings_id'), table_name='build_plan_shippings')
    op.drop_index(op.f('ix_build_plan_shippings_build_plan_id'), table_name='build_plan_shippings')
    op.drop_table('build_plan_shippings')
    op.drop_index('ix_build_plan_revisions_chrono', table_name='build_plan_revisions')
    op.drop_table('build_plan_revisions')
    op.drop_index(op.f('ix_build_plan_components_id'), table_name='build_plan_components')
    op.drop_index('ix_build_plan_components_component_id', table_name='build_plan_components')
    op.drop_index(op.f('ix_build_plan_components_build_plan_id'), table_name='build_plan_components')
    op.drop_table('build_plan_components')
    op.drop_index('ix_build_plan_build_requests_build_plan_id', table_name='build_plan_build_requests')
    op.drop_table('build_plan_build_requests')
    op.drop_table('build_plan_build_notes')
    op.drop_index(op.f('ix_build_plan_access_overrides_id'), table_name='build_plan_access_overrides')
    op.drop_table('build_plan_access_overrides')
    op.drop_table('user_build_requests')
    op.drop_table('log_report_attachments')
    op.drop_index(op.f('ix_build_plans_year'), table_name='build_plans')
    op.drop_index(op.f('ix_build_plans_work_week'), table_name='build_plans')
    op.drop_index('ix_build_plans_support_activity_id', table_name='build_plans')
    op.drop_index('ix_build_plans_status', table_name='build_plans')
    op.drop_index('ix_build_plans_ship_date', table_name='build_plans')
    op.drop_index(op.f('ix_build_plans_latest_revision_id'), table_name='build_plans')
    op.drop_index(op.f('ix_build_plans_is_imported'), table_name='build_plans')
    op.drop_index('ix_build_plans_family_form_factor_id', table_name='build_plans')
    op.drop_index('ix_build_plans_config_number_id', table_name='build_plans')
    op.drop_index('ix_build_plans_build_start_date', table_name='build_plans')
    op.drop_table('build_plans')
    op.drop_index(op.f('ix_build_plan_import_si_rows_import_file_id'), table_name='build_plan_import_si_rows')
    op.drop_index(op.f('ix_build_plan_import_si_rows_id'), table_name='build_plan_import_si_rows')
    op.drop_index('ix_build_plan_import_si_rows_file', table_name='build_plan_import_si_rows')
    op.drop_table('build_plan_import_si_rows')
    op.drop_index(op.f('ix_build_plan_import_shipping_infos_import_file_id'), table_name='build_plan_import_shipping_infos')
    op.drop_index(op.f('ix_build_plan_import_shipping_infos_id'), table_name='build_plan_import_shipping_infos')
    op.drop_index('ix_build_plan_import_shipping_infos_file', table_name='build_plan_import_shipping_infos')
    op.drop_table('build_plan_import_shipping_infos')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_stored_file_file_id'), table_name='stored_file')
    op.drop_table('stored_file')
    op.drop_index(op.f('ix_shippings_status'), table_name='shippings')
    op.drop_index(op.f('ix_shippings_recipient_user_id'), table_name='shippings')
    op.drop_index(op.f('ix_shippings_id'), table_name='shippings')
    op.drop_index(op.f('ix_shippings_config_number_id'), table_name='shippings')
    op.drop_table('shippings')
    op.drop_index('ix_shipping_import_files_status', table_name='shipping_import_files')
    op.drop_index(op.f('ix_shipping_import_files_id'), table_name='shipping_import_files')
    op.drop_index('ix_shipping_import_files_created_at', table_name='shipping_import_files')
    op.drop_index(op.f('ix_shipping_import_files_content_hash'), table_name='shipping_import_files')
    op.drop_table('shipping_import_files')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_pm_families_user_id'), table_name='pm_families')
    op.drop_index('ix_pm_families_user_family', table_name='pm_families')
    op.drop_index(op.f('ix_pm_families_id'), table_name='pm_families')
    op.drop_index(op.f('ix_pm_families_family_id'), table_name='pm_families')
    op.drop_table('pm_families')
    op.drop_table('log_reports')
    op.drop_index('ix_csf_family', table_name='component_supplier_families')
    op.drop_index('ix_csf_component_supplier', table_name='component_supplier_families')
    op.drop_table('component_supplier_families')
    op.drop_index(op.f('ix_build_requests_status'), table_name='build_requests')
    op.drop_index(op.f('ix_build_requests_requestor_id'), table_name='build_requests')
    op.drop_index(op.f('ix_build_requests_family_form_factor_id'), table_name='build_requests')
    op.drop_index(op.f('ix_build_requests_config_number_id'), table_name='build_requests')
    op.drop_table('build_requests')
    op.drop_index('ix_build_plan_import_files_status', table_name='build_plan_import_files')
    op.drop_index(op.f('ix_build_plan_import_files_id'), table_name='build_plan_import_files')
    op.drop_index('ix_build_plan_import_files_created_at', table_name='build_plan_import_files')
    op.drop_index(op.f('ix_build_plan_import_files_content_hash'), table_name='build_plan_import_files')
    op.drop_table('build_plan_import_files')
    op.drop_index(op.f('ix_build_plan_access_access_id'), table_name='build_plan_access')
    op.drop_table('build_plan_access')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_record_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_module_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_details_id'), table_name='test_details')
    op.drop_table('test_details')
    op.drop_table('support_activity_build_notes')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_family_form_factors_id'), table_name='family_form_factors')
    op.drop_table('family_form_factors')
    op.drop_table('component_suppliers')
    op.drop_index(op.f('ix_component_slots_id'), table_name='component_slots')
    op.drop_table('component_slots')
    op.drop_table('build_plan_build_descs')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_tests_name'), table_name='tests')
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_support_activities_name'), table_name='support_activities')
    op.drop_table('support_activities')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_silicon_steppings_name'), table_name='silicon_steppings')
    op.drop_table('silicon_steppings')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_forwarders_name'), table_name='forwarders')
    op.drop_index(op.f('ix_forwarders_id'), table_name='forwarders')
    op.drop_table('forwarders')
    op.drop_index(op.f('ix_form_factors_name'), table_name='form_factors')
    op.drop_index(op.f('ix_form_factors_id'), table_name='form_factors')
    op.drop_table('form_factors')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_index(op.f('ix_families_code'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_config_numbers_value'), table_name='config_numbers')
    op.drop_table('config_numbers')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_table('components')
    op.drop_table('build_notes')
    op.drop_table('attribute_definitions')
    op.drop_index(op.f('ix_action_categories_id'), table_name='action_categories')
    op.drop_table('action_categories')
    # ### end Alembic commands ###
