"""iniatialize table

Revision ID: cdd2d4d4c877
Revises: 
Create Date: 2026-04-11 00:53:05.269484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd2d4d4c877'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_date',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date_id'),
    sa.UniqueConstraint('full_date')
    )
    op.create_index(op.f('ix_dim_date_date_id'), 'dim_date', ['date_id'], unique=False)
    op.create_table('dim_statement',
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('statement_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('statement_id'),
    sa.UniqueConstraint('statement_name')
    )
    op.create_index(op.f('ix_dim_statement_statement_id'), 'dim_statement', ['statement_id'], unique=False)
    op.create_table('dim_stock',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('stock_number', sa.Text(), nullable=False),
    sa.Column('stock_name', sa.Text(), nullable=False),
    sa.Column('weblink', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('stock_code'),
    sa.UniqueConstraint('stock_number')
    )
    op.create_index(op.f('ix_dim_stock_stock_id'), 'dim_stock', ['stock_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('dim_metric',
    sa.Column('metric_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('metric_path', sa.Text(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('parent_metric_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_metric_id'], ['dim_metric.metric_id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['dim_statement.statement_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_dim_metric_metric_id'), 'dim_metric', ['metric_id'], unique=False)
    op.create_index(op.f('ix_dim_metric_metric_path'), 'dim_metric', ['metric_path'], unique=True)
    op.create_table('stored_file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('storage_path'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_stored_file_file_id'), 'stored_file', ['file_id'], unique=False)
    op.create_table('fact_financial_values',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.BigInteger(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['dim_metric.metric_id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['dim_statement.statement_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['dim_stock.stock_id'], ),
    sa.PrimaryKeyConstraint('stock_id', 'metric_id', 'statement_id', 'date_id')
    )
    op.create_table('import_job',
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.Enum('DIM_METRIC', 'DIM_STOCK', 'DIM_STATEMENT', 'DIM_DATE', 'FACT_FINANCIAL_VALUES', name='import_table_name_enum'), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_type', sa.Enum('CSV', 'XLSX', name='file_type_enum'), nullable=False),
    sa.Column('replace_all', sa.Boolean(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('duplicates_in_file', sa.Integer(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('imported_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['stored_file.file_id'], ),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('import_job_id')
    )
    op.create_index(op.f('ix_import_job_import_job_id'), 'import_job', ['import_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_job_import_job_id'), table_name='import_job')
    op.drop_table('import_job')
    op.drop_table('fact_financial_values')
    op.drop_index(op.f('ix_stored_file_file_id'), table_name='stored_file')
    op.drop_table('stored_file')
    op.drop_index(op.f('ix_dim_metric_metric_path'), table_name='dim_metric')
    op.drop_index(op.f('ix_dim_metric_metric_id'), table_name='dim_metric')
    op.drop_table('dim_metric')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dim_stock_stock_id'), table_name='dim_stock')
    op.drop_table('dim_stock')
    op.drop_index(op.f('ix_dim_statement_statement_id'), table_name='dim_statement')
    op.drop_table('dim_statement')
    op.drop_index(op.f('ix_dim_date_date_id'), table_name='dim_date')
    op.drop_table('dim_date')
    # ### end Alembic commands ###
